apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins-gitops
  name: jenkins-gitops
spec:
  replicas: 
  selector:
    matchLabels:
      app: jenkins-gitops
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins-gitops
    spec:
      containers:
      - image: rajputmarch2020/test:latest
        name: jenkins-gitops
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: jenkins-gitops